const PDFDocument = require('pdfkit');

const generateTicketPdfBuffer = (booking) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', (error) => reject(error));

    const event = booking.eventId || {};
    const user = booking.userId || {};

    doc
      .fontSize(24)
      .fillColor('#0f766e')
      .text('Smart Event Booking', { align: 'left' })
      .moveDown(0.3)
      .fontSize(14)
      .fillColor('#1f2937')
      .text('Official Ticket')
      .moveDown(1.2);

    doc
      .roundedRect(50, 130, 500, 280, 12)
      .lineWidth(1)
      .strokeColor('#cbd5e1')
      .stroke();

    doc
      .fontSize(16)
      .fillColor('#111827')
      .text(event.title || 'Event', 70, 160)
      .moveDown(0.4)
      .fontSize(11)
      .fillColor('#475569')
      .text(`Ticket ID: ${booking.ticketId}`, 70)
      .text(`Booked By: ${user.name || 'User'} (${user.email || ''})`, 70)
      .text(`Event Date: ${event.date ? new Date(event.date).toLocaleString('en-US') : 'TBA'}`, 70)
      .text(`Event Location: ${event.location || 'TBA'}`, 70)
      .text(`Seats Booked: ${booking.seatsBooked}`, 70)
      .text(`Booking Date: ${new Date(booking.bookingDate).toLocaleString('en-US')}`, 70);

    doc
      .moveDown(1.5)
      .fontSize(10)
      .fillColor('#64748b')
      .text('Please carry a valid ID and this ticket at the venue entrance.', 70)
      .moveDown(0.4)
      .text('This ticket is generated by Smart Event Management and Ticket Booking System.', 70);

    doc.end();
  });
};

module.exports = {
  generateTicketPdfBuffer
};
